name: CI
on:
  push: 
  branches: [ main ]
  pull_request: [ main ]
  workflow_displatch:
  jobs:
  build:
    runs-on: ubunutu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line scripts
        run: echo Hell0
      - name: Run a multi-line script
        run: |
         echo Add other actions
         echo test, and deploy your build
  
